version: "3.8"

services:
  aura-3d-mongo:
    image: mongo:latest
    container_name: aura-3d-mongo
    restart: unless-stopped
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./data/mongo:/data/db
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - "27017:27017"
    networks:
      - aura-3d-network

  aura-3d-api:
    image: jxnatang7/aura-3d-api:latest
    container_name: aura-3d-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      aura-3d-mongo:
        condition: service_healthy
    networks:
      - aura-3d-network

networks:
  aura-3d-network:
    driver: bridge
