import { createTheme } from "@shopify/restyle";
import pallete from "./pallete";

const lightColors = {
  ...pallete,
  mainBackground: pallete.black,
  mainTitle: pallete.titleLight,
  mainText: pallete.textDark,
  buttonBackground: pallete.buttonBackgroundLight,
  inputBackground: pallete.inputBackgroundLight,
  inputText: pallete.inputTextLight,
  backgroundGradient0: pallete.gradientLight1,
  backgroundGradient1: pallete.gradientLight2,
  myMessageBackground: pallete.buttonBackgroundLight,
};

const darkColors: typeof lightColors = {
  ...pallete,
  mainBackground: pallete.black,
  mainTitle: pallete.titleDark,
  mainText: pallete.textDark,
  buttonBackground: pallete.buttonBackgroundDark,
  inputBackground: pallete.inputBackgroundDark,
  inputText: pallete.inputTextDark,
  backgroundGradient0: pallete.gradientDark0,
  backgroundGradient1: pallete.gradientDark1,
  myMessageBackground: pallete.buttonBackgroundDark,
};

const theme = createTheme({
  breakpoints: {
    smallPhone: 0,
    phone: 400,
    tablet: 768,
    desktop: 1024,
  },
  colors: lightColors,
  spacing: {
    none: 0,
    xs: 4,
    s: 6,
    sm: 10,
    m: 16,
    ml: 20,
    l: 24,
    xl: 40,
    xxl: 64,
    xxxl: 80,
    xxxxl: 120,
    minus: -10,
  },
  imageVariants: {
    model: {
      width: "100%",
      height: "100%",
    },
    default: {
      width: 40,
      height: 40,
    },
    defaults: {
      width: 40,
      height: 40,
    },
    init: {
      width: 262,
      height: 271,
      marginTop: {
        smallPhone: 0,
        phone: "xxxxl",
      },
    },
  },
  containerVariants: {
    chip: {
      maxWidth: 300,
      height: 40,
      p: "s",
      borderRadius: 4,
      backgroundColor: "mainBackground",
    },
    defaults: {
      flex: 1,
      p: "m",
      pt: "xl",
      alignItems: "center",
      backgroundColor: "transparent",
    },
    chat: {
      flex: 1,
      px: "l",
      pt: "xl",
      pb: "none",
      alignItems: "center",
      backgroundColor: "allBlack",
    },
    screen: {
      flex: 1,
      width: "100%",
      padding: "none",
      backgroundColor: "transparent",
    },
  },
  boxVariants: {
    screen: {
      flex: 1,
      backgroundColor: "mainBackground",
    },
  },
  pressableVariants: {
    input: {
      fontFamily: "Sekuya-Regular",
      backgroundColor: "inputBackgroundLight",
      color: "inputBackground",
      flex: 1,
      width: "100%",
      minHeight: 40,
      borderRadius: 6,
      p: "s",
      fontSize: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: "s",
    },
    transparent: {
      backgroundColor: "transparent",
    },
    chip: {
      maxWidth: 400,
      alignItems: "center",
      justifyContent: "center",
      p: "s",
      borderRadius: 4,
      backgroundColor: "transparent",
      mr: "s",
    },
    default: {
      backgroundColor: "buttonBackgroundLight",
    },
    defaults: {
      backgroundColor: "buttonBackgroundLight",
    },
  },
  buttonVariants: {
    imageOption: {
      backgroundColor: "transparent",
      borderRadius: 28,
      width: 200,
      height: 200,
      alignItems: "center",
      justifyContent: "center",
      borderColor: "gray900",
      borderWidth: 1,
    },
    createModel: {
      width: 70,
      height: 70,
      borderRadius: 50,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
      position: "absolute",
      bottom: 30,
    },
    success: {
      backgroundColor: "transparent",
      color: "buttonTextLight",
    },
    red: {
      backgroundColor: "transparent",
      color: "buttonTextLight",
    },
    transparent: {
      backgroundColor: "transparent",
      color: "buttonTextGray",
    },
    chipDisabled: {
      width: "auto",
      minWidth: 100,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: "m",
      borderRadius: 20,
      color: "buttonTextLight",
      borderWidth: 1,
      borderColor: "gray800",
      opacity: 0.5,
      backgroundColor: "transparent",
    },
    chip: {
      width: "auto",
      minWidth: 100,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: "m",
      borderRadius: 20,
      backgroundColor: "transparent",
      color: "buttonTextLight",
      borderWidth: 1,
      borderColor: "gray800",
    },
    chipActive: {
      width: "auto",
      minWidth: 100,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: "m",
      borderRadius: 20,
      backgroundColor: "transparent",
    },
    icon: {
      backgroundColor: "transparent",
      color: "buttonTextLight",
      alignItems: "center",
      justifyContent: "center",
      width: 50,
      height: 50,
    },
    default: {
      backgroundColor: "transparent",
      color: "buttonTextLight",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 30,
      width: "85%",
      maxWidth: 450,
      height: {
        smallPhone: 50,
        phone: 60,
      },
    },
    defaults: {
      backgroundColor: "transparent",
      color: "buttonTextLight",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 30,
      width: "85%",
      maxWidth: 450,
      height: {
        smallPhone: 50,
        phone: 60,
      },
    },
    primary: {
      backgroundColor: "transparent",
      color: "buttonTextLight",
      borderRadius: 30,
    },
    secondary: {
      backgroundColor: "transparent",
      color: "buttonTextDark",
      borderRadius: 30,
    },
    cameraOption: {
      width: {
        smallPhone: 40,
        phone: 50,
      },
      height: {
        smallPhone: 40,
        phone: 50,
      },
      borderRadius: 10,
      backgroundColor: "transparent",
      color: "buttonTextGray",
      borderWidth: 2,
      borderColor: "buttonBackgroundGray",
    },
  },
  textVariants: {
    modelName: {
      color: "mainText",
      fontFamily: "StackSansNotch-Bold",
      fontSize: 20,
    },
    modelUser: {
      color: "gray300",
      fontFamily: "StackSansNotch-Bold",
      fontSize: 16,
    },
    subHeader: {
      color: "mainText",
      fontFamily: "StackSansNotch-Medium",
      fontSize: 18,
    },
    "label-error": {
      width: "100%",
      fontFamily: "Sekuya-Regular",
      fontSize: 14,
      color: "error",
    },
    label: {
      color: "mainText",
      fontFamily: "StackSansNotch-Medium",
      fontSize: 14,
    },
    header2: {
      color: "mainText",
      fontFamily: "StackSansNotch-Medium",
      fontSize: 16,
      lineHeight: 24,
      textAlign: "center",
    },
    messageTime: {
      fontFamily: "StackSansNotch-Medium",
      fontSize: 12,
    },
    message: {
      fontFamily: "StackSansNotch-Medium",
      fontSize: 16,
      lineHeight: 24,
    },
    containerHeader: {
      color: "mainText",
      fontFamily: "MulishFontBold",
      fontSize: 24,
    },
    button: {
      fontFamily: "MulishFontMedium",
      fontSize: {
        smallPhone: 16,
        phone: 18,
      },
      color: "buttonTextLight",
    },
    header: {
      color: "mainText",
      fontFamily: "StackSansNotch-Bold",
      fontSize: {
        smallPhone: 20,
        phone: 30,
      },
      textAlign: "center",
    },
    "sub-header": {
      color: "mainText",
      fontFamily: "StackSansNotch-Bold",
      fontSize: {
        smallPhone: 18,
        phone: 24,
      },
      textAlign: "center",
    },
    body: {
      fontFamily: "MulishFontMedium",
      color: "mainText",
      fontSize: {
        smallPhone: 14,
        phone: 16,
      },
      lineHeight: 24,
    },
    messageOption: {
      fontFamily: "StackSansNotch-Medium",
      color: "textLight",
      fontSize: {
        smallPhone: 14,
        phone: 16,
      },
      lineHeight: 24,
    },
    defaults: {},
    infoTitle: {
      color: "mainText",
      fontFamily: "StackSansNotch-Bold",
      fontSize: 16,
    },
    listItemTitle: {
      color: "textLight",
      fontFamily: "StackSansNotch-Bold",
      fontSize: 16,
    },
    infoSubtitle: {
      fontFamily: "Sekuya-Regular",
      fontSize: 14,
      color: "textGray",
    },
  },
  textInputVariants: {
    iconRigth: {
      fontFamily: "Sekuya-Regular",
      backgroundColor: "inputBackgroundLight",
      color: "inputTextLight",
      flex: 1,
      height: 40,
      borderTopLeftRadius: 6,
      borderBottomLeftRadius: 6,
      borderBottomRightRadius: 0,
      borderTopRightRadius: 0,
      p: "s",
      maxWidth: 450,
      fontSize: 16,
    },
    iconLeft: {
      fontFamily: "Sekuya-Regular",
      backgroundColor: "inputBackgroundLight",
      color: "inputTextLight",
      flex: 1,
      height: 40,
      maxWidth: 450,
      borderTopLeftRadius: 0,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 6,
      borderTopRightRadius: 6,
      p: "s",
      fontSize: 16,
    },
    default: {
      fontFamily: "StackSansNotch-Medium",
      backgroundColor: "inputBackgroundLight",
      color: "inputTextLight",
      flex: 1,
      maxWidth: 450,
      height: 40,
      borderRadius: 6,
      p: "s",
      fontSize: 16,
    },
    primary: {
      fontFamily: "Sekuya-Regular",

      backgroundColor: "inputBackgroundLight",
      color: "inputTextLight",
    },
    secondary: {
      fontFamily: "Sekuya-Regular",

      backgroundColor: "inputBackgroundDark",
      color: "inputTextDark",
    },
    code: {
      fontFamily: "StackSansNotch-Bold",
      backgroundColor: "inputBackgroundLight",
      color: "inputText",
      width: {
        smallPhone: 30,
        phone: 35,
        desktop: 40,
      },
      height: {
        smallPhone: 30,
        phone: 35,
        desktop: 40,
      },
      borderRadius: "50%",
      textAlign: "center",
      fontSize: 40,
    },
  },
  flashListVariants: {
    messages: {
      backgroundColor: "transparent",
      width: "100%",
      maxHeight: 800,
    },
    default: {
      backgroundColor: "backgroundLight",
      width: "100%",
      maxWidth: 450,
      maxHeight: 800,
    },
    defaults: {
      backgroundColor: "backgroundLight",
      width: "100%",
      maxWidth: 450,
      maxHeight: 800,
    },
    messageOptions: {
      width: "100%",
      backgroundColor: "transparent",
      height: 40,
      maxHeight: 40,
    },
    "models-vertical": {
      flex: 1,
      marginTop: "m",
      maxWidth: "100%",
      backgroundColor: "transparent",
    },
    "models-horizontal": {
      overflow: "auto",
      backgroundColor: "transparent",
    },
  },
  cameraVariants: {
    defaults: {
      width: 40,
      height: 40,
    },
    code: {
      flex: 1,
      width: "100%",
      height: "100%",
    },
  },
  buttonGradients: {
    primary: ["buttonGradientPrimary0", "buttonGradientPrimary1"],
    secondary: ["buttonGradientSecondary0", "buttonGradientSecondary1"],
    red: ["finish", "finish"],
    default: ["gradientLight0", "gradientLight1"],
    transparent: ["transparent", "transparent"],
  },
  cardVariants: {
    header: {
      width: "100%",
      paddingHorizontal: "s",
      backgroundColor: "transparent",
    },
    default: {
      backgroundColor: "backgroundLight",
      borderRadius: 8,
    },
    defaults: {
      backgroundColor: "backgroundLight",
      borderRadius: 8,
    },
    transparent: {
      backgroundColor: "transparent",
      borderRadius: 8,
    },
    primary: {
      backgroundColor: "buttonGradientPrimary1",
      borderRadius: 8,
    },
    secondary: {
      backgroundColor: "buttonGradientSecondary1",
      borderRadius: 8,
    },
    "model-horizontal": {
      backgroundColor: "transparent",
      marginHorizontal: "s",
      justifyContent: "center",
      alignItems: "center",
      width: 200,
      height: 200,
    },
    "model-vertical": {
      backgroundColor: "transparent",
      marginHorizontal: "s",
      justifyContent: "center",
      alignItems: "center",
    },
    modelInfo: {
      width: "100%",
      height: 80,
      backgroundColor: "transparent",
      marginHorizontal: "s",
      flexDirection: "row",
      justifyContent: "space-between",
      padding: "m",
      alignItems: "center",
      gap: "m",
      overflow: "hidden",
      borderRadius: 12,
    },
  },
});

export type Theme = typeof theme;

export const darkTheme: Theme = {
  ...theme,
  colors: darkColors,
};

export default theme;
