apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  # DB_URL: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo-service:27017/aura-3d?authSource=admin"
  PORT: "3001"
  DB_URL: "${MONGO_URI}"
  JWT_SECRET_KEY: "${JWT_SECRET}"
  MESHY_AI_URL: "${MESHY_AI_URL}"
  MESHY_API_KEY: "${MESHY_API_KEY}"
