name: Deploy to Production

on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/backend
          push: true
          tags: jxnatang7/aura-3d-api:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: |
          cat <<EOF > ~/apps/aura-3d/backend/.env
          NODE_ENV=production
          PORT=3001
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET }}
          DB_URL=${{ secrets.MONGO_URI }}
          MESHY_AI_URL=${{ secrets.MESHY_AI_URL }}
          MESHY_API_KEY=${{ secrets.MESHY_API_KEY }}
          EOF
      - name: Setup and Run Docker Compose
        run: |
          mkdir -p ~/apps/aura-3d/backend/docker/mongo

          cp apps/backend/docker-compose.prod.yaml ~/apps/aura-3d/backend/docker-compose.yaml
          cp apps/backend/docker/mongo/init-mongo.sh ~/apps/aura-3d/backend/docker/mongo/

          cd ~/apps/aura-3d/backend

          docker compose pull aura-3d-api
          docker compose up -d

          docker image prune -f
