name: Deploy to Kubernetes Production

on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/backend
          push: true
          tags: jxnatang7/aura-3d-api:latest

  deploy-k8s:
    needs: build-and-push
    runs-on: self-hosted
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MESHY_API_KEY: ${{ secrets.MESHY_API_KEY }}
      MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME || 'admin' }}
      MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD || 'admin' }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Docker Registry Secret in K8s
        run: |
          k3s kubectl delete secret regcred --ignore-not-found

          k3s kubectl create secret docker-registry regcred \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=$DOCKER_USERNAME \
            --docker-password=$DOCKER_PASSWORD \
            --docker-email=${DOCKER_EMAIL}

      - name: Deploy Manifests
        run: |
          cd k8s

          envsubst < mongo-config.yaml | k3s kubectl apply -f -
          envsubst < api-config.yaml | k3s kubectl apply -f -

          k3s kubectl apply -f mongo-service.yaml
          k3s kubectl apply -f mongo-statefulset.yaml

          k3s kubectl apply -f api-service.yaml
          k3s kubectl apply -f ingress.yaml

          k3s kubectl apply -f api-deployment.yaml

      - name: Force Rollout Restart
        run: |
          k3s kubectl rollout restart deployment/aura-3d-api
          k3s kubectl rollout status deployment/aura-3d-api
